### ISSUE TITLE
Divergence of the power spectra with the larger supercell

### ISSUE THREAD

**Issue by ballal09** [abelcarreras/DynaPhoPy#17]
Dear Abel Carreras

I hope you are doing well.  I have run into an issue when I was trying to compute the full power spectrum for a larger MD supercell. When I have calculated the full power spectrum for 1 1 4 supercell (120 atoms), I have found a good match with the harmonic dos (of course 1 1 4 supercell as well). But, When I increased the supercell to 2 2 4 (480 atoms), I have found that the high frequency regime of the power spectrum does not match with the harmonic phonon dos for 2 2 4 supercell  although there is some similarity. I have attached the two plots here for your reference. Please let me know your thoughts on this.  For your information, I have used 30 ps of trajectories  (1 fs timestep) to calculate the power spectrum for both supercell. Therefore, I am thinking the length of the simulation may not be an issue. Thank you very much for your time.

![FPS_T100K_S114](https://user-images.githubusercontent.com/60304718/177080287-45ca2a79-0d65-4414-af4a-4ec9342e9a03.png)
![FPS_T100K_S224_N30000](https://user-images.githubusercontent.com/60304718/177080319-a53c3c0c-47c5-4190-976b-9e1a6244f39b.png)

Best
Ballal

**Comment by abelcarreras** [comment]
I think the issue could be an effect of attaching MD trajectories.
The joint between trajectories can introduce some high frequency artifacts. I have not tested this extensively so I don't know the magnitude of this effect. In general I think this effect should be small but it may depend on the system.
Things you can check:
1) Compute the full power spectrum of the individual MD and check if the issue is also present.
2) Make sure the individual MD are properly converged. The artifacts introduced in the trajectory joints may be amplified by not completely converged MD. Maybe you can use "--read_from" option to test different equilibration times and check if this issue is minimized or not.

**Comment by abelcarreras** [comment]
1. If I understood correctly you computed the full power spectrum joining several MD trajectories right? The idea is to check the full power spectrum using a single MD trajectory.
2. But these trajectories are completely independent right? If that is the case at the joints it should be a discontinuity in the positions and velocities.

**Comment by abelcarreras** [comment]
Ok, then if the trajectory is correct maybe there is some bug in the code.
Can you send me a minimal example that shows the issue so I can reproduce it in my computer?

**Comment by ballal09** [comment]
Dear Abel Carreras

I hope you are doing well. I have attached here<https://drive.google.com/drive/folders/1W9AzqqeuooeDlmLlLjBqVC-JXRxIbxBE?usp=sharing> the minimal data to reproduce the problem for the lager supercell (2 2 4) which includes POSCAR of the unit cell,  Force set file for 2 2 4 supercell from phonopy,  input file and XDATCAR file.  XDATCAR file contains the 30 ps of continuous trajectories with 1 fs time step.  Please let me know if you need any further information. Thank you very much for your time.

Best
Ballal Ahammed

________________________________

**Comment by abelcarreras** [comment]
Hi @ballal09,

I found the issue. The point is that the order of atoms in the supercell is not correct. In order to compute the atomic displacements Dyanphopy requieres the atoms of the supercell to be in a particular order respect to the unit cell. This order is the same as the supercells generated using phonopy.

You can generate a "proper" supercell from a unitcell using **-c_poscar** option in dynaphopy. It is recommended to first generate the supercell using dynaphopy and then run the MD using this supercell. 

However if the simulation is already done, as an alternative, you can run Dynaphopy using  the tag **--auto_order** to try to guess the atoms order from the MD data. This may not work in all cases but fortunately, in your case, it worked and I was able to generate the proper full power spectrum. 

The way to check that the atoms order has been taken correctly is to do a Maxwell-Boltzmann analysis. This plots the distribution of atomic velocities and fits it to a MB distribution. If you observe that the distribution is well fitted to the MB curve with the temperature you set in your simulation then the order is most likely right.

**Comment by ballal09** [comment]
Dear Abel Carreras

It was really helpful! I have fixed the problem. Thank you so much for your time and help!

Best
Ballal
