### ISSUE TITLE
Full power spectra becomes noisier with increasing simulations length + odd behaviour with temperature

### ISSUE THREAD

**Issue by gabkrenzer** [abelcarreras/DynaPhoPy#22]
Hi Abel, 

I have two issues. 

1. The full power spectra become noisier when I increase the simulation length. This doesn't seem due to the concatenation though since the power spectra for simulations using dt={500ps, 1ns, 1.5ns}, all yielded the same result. I also concatenated the files using concath5, so I would assume this is done in the most consistent way with how dynaphopy works. Here, I just took the raw data from dynaphopy for the power spectra. I didn't multiply by any factor since it seemed to match the DOS, so I assumed this was already done by dynaphopy.
![image](https://user-images.githubusercontent.com/52633008/216370049-1a32ffdb-e3be-4a99-95cc-3df5118f15bf.png)

3. When I change the temperature, however, I see a large increase in the power spectra values
![image](https://user-images.githubusercontent.com/52633008/216370512-0475e578-b863-4949-958a-ebff1f7360f0.png)
But then when I add a factor of 1/(3*n_atoms*k_b*T), I get odd results where high temperature spectra are kind of matching, but not lower T spectra.
![image](https://user-images.githubusercontent.com/52633008/216370987-9eb162f6-83bd-4268-8a64-10d603077277.png)
I seem to get a similar problem than raised here (https://github.com/abelcarreras/DynaPhoPy/issues/17) since at higher frequency for the noisy high T spectra I get very large power spectra values in a similar way. Nevertheless, I produced my supercells using phonopy so the atoms should be rightly ordered. You mentioned there an `--auto_order` tag. Is there an equivalent I could use in a python script?

Many Thanks, 
Gabriel

**Comment by abelcarreras** [comment]
As for auto_order you have to use `check_atoms_order` function to get an atoms **template** (that contains the order) and then use it in the trajectory reading function. You can use a structure similar to the one written here:

https://github.com/abelcarreras/DynaPhoPy/blob/70ae51aef695f1bac9f01d4d7f6bb5e3e63ad65b/scripts/dynaphopy#L247

**Comment by gabkrenzer** [comment]
Hi Abel, 
The atoms do exchange sites during the MD, however, I don't understand how that would cause the power spectra to essentially become nonsense? The power spectra should only be based on the velocity auto-correllation functions and shouldn't need any kind of projection onto sites? Or are you doing some symmeterisation under the hood within dynaphopy?

**Comment by abelcarreras** [comment]
In theory I would say you are right, but at practice, since you sample the MD at a finite rate I guess that the discrete Fourier transform  may give you some artifacts if the atoms exchange sites. I can imagine in the limit where the atoms move almost freely the Fourier transform of a non oscillating velocity would give basically non-sense. In these cases reducing the time step should help.

**Comment by gabkrenzer** [comment]
I don't think that's true in general for velocity auto-correlation functions. Maybe it is for dynaphopy because of the way they are computed. But in general people have been able to compute power spectra with other codes when diffusion occurs, see https://onlinelibrary.wiley.com/doi/epdf/10.1002/adts.202000240. Also, from a theoretical point of view, if the atoms are moving freely then the velocoty auto-correlation is constant and the Fourier Transform should be a delta function (https://dsp.stackexchange.com/questions/40733/what-is-the-fourier-transform-of-a-constant-signal), which would look weird for sure but that is a well-known physical result. For instance, you can usually extract the diffusion coefficient from a power spectra at zero frequency.

**Comment by gabkrenzer** [comment]
Dynaphopy is probably not suited for what I am trying to do.

**Comment by abelcarreras** [comment]
I understand that it can be done, and for the full PS it should be no problem for the atoms to exchange. However since for the power spectrum the area under the curve corresponds to the vibrational kinetic energy, If you have a component of the kinetic energy that is not vibrational (atoms diffusion) this will correspond to zero frequency in the PS. In my understanding at practice this is be very difficult to sample and in general you will not see it in the computed PS. I guess that if part of the kinetic energy is not seen in the PS then the sample of the non zero frequencies will be worse and the normalization of the PS gets messed up. I have no experience in these kind of analysis so I don't know how to help you improve the results. 
What is also true is that dynaphopy was not designed for situations where atoms diffuse (since for the projections it assumes that the atoms are always oscillating around the same site) and I never explored this cases.
