### ISSUE TITLE
How to run the dynaphopy by openmp

### ISSUE THREAD

**Issue by ZengZezhu** [abelcarreras/DynaPhoPy#9]
Hi, professor.

I would like to use the dynaphopy by openmp, but when I reinstall the dynaphopy by command like "python setup_openmp.py install --user",  I cannot find the setup_openmp.py file and there is only setup.py file.

I tried to load the python/3.7.0 and gcc/6.3.0 in the supercomputer system and then used the command:

"python setup.py install --user"  to install.

The installation is successful and I found the prompt information indicates that the openmp is used to install. 
But when I used the command like:

mpirun -np 36 dynaphopy input_file dump.traj -sdata 

to run the dynaphopy, I found there is no reaction to my command. But if I used:

dynaphopy input_file dump.traj -sdata 

it can run slowly. 

Could you tell me how to run the dynaphopy by openmp (multiple cores)?

Best,
zezhu

**Comment by ZengZezhu** [comment]
Hi, Professor.

I solved this problem by myself.:) It is the issue from openmp.

Best,
Zezhu

**Comment by XIANG-Xing** [comment]
Hi, Zezhu, could I ask whether you solve this problem? I find dynaphopy is automatically installed with openmp, but I do not know how to run it using openmp. I have tried "export OMP_NUM_THREADS=16" before command, while it does not work. Could you give me some suggestions? Thanks in advance.

**Comment by XiangXing96** [comment]
Hi Zezhu,

I get it. Thank you very much for the reply.

best regards

**Comment by abelcarreras** [comment]
Hi all,

Dynaphopy is implemented with openMP support but only for the maximum entropy method (power_spectrum_algorithm=1) . For FFT (power_spectrum_algorithm=2) I use numpy so it depends on your installation of numpy. If I remember correctly conda includes the openmp compiled version of numpy. Also you can use FFTW with power_spectrum_algorithm=3  (here also it depends on your FFTW build ) and GPU (cuda) using power_spectrum_algorithm=4. 

As a side note, if you compile dynaphopy form source you will need to use GCC otherwise it compiles the non-parallel version. If you use another compiler you will need to modify setup.py.
